name: Build Android APK

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 30  # Увеличиваем таймаут

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip openjdk-8-jdk git zip unzip wget

    - name: Install Buildozer
      run: pip3 install buildozer

    - name: Pre-download Android NDK 21e
      run: |
        mkdir -p ~/.buildozer/android/platform
        cd ~/.buildozer/android/platform
        wget -q https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip
        unzip -q android-ndk-r21e-linux-x86_64.zip
        rm android-ndk-r21e-linux-x86_64.zip
        echo "NDK downloaded successfully"

    - name: Build APK
      run: |
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: vahot-app
        path: bin/*.apk
