name: Build Android APK

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache Android SDK/NDK
      uses: actions/cache@v4
      with:
        path: |
          ~/.buildozer
          ~/.gradle
        key: ${{ runner.os }}-android-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-android-

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip openjdk-8-jdk git zip unzip wget
        pip3 install buildozer cython

    - name: Install Buildozer
      run: pip3 install buildozer

    - name: Build with retry and timeout
      run: |
        export BUILDODER_DOWNLOAD_TIMEOUT=300
        for i in 1 2 3; do
          echo "Build attempt $i"
          timeout 20m buildozer -v android debug && break
          echo "Build failed or timed out, retrying..."
          sleep 10
        done

        name: Build APK
        run: |
        buildozer -v android debug

        name: Find and list APK files
        run: |
        echo "=== Searching for APK files ==="
        find . -name "*.apk" -type f
        echo "=== Contents of current directory ==="
        ls -la
        echo "=== Contents of .buildozer ==="
        ls -la .buildozer/android/platform/*/build/outputs/apk/ 2>/dev/null || echo "APK directory not found"
        
    - name: Debug - Check build results
      run: |
        echo "=== Checking build directory ==="
        find . -name "*.apk" -type f | head -10
        echo "=== Checking bin directory ==="
        ls -la bin/ || echo "bin directory not found"
        echo "=== Checking .buildozer directory ==="
        find .buildozer -name "*.apk" -type f 2>/dev/null | head -10
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: vahot-app
        path: bin/*.apk
