name: Build Android APK

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache Android SDK/NDK
      uses: actions/cache@v4
      with:
        path: |
          ~/.buildozer
          ~/.gradle
        key: ${{ runner.os }}-android-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-android-

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip openjdk-8-jdk git zip unzip wget

    - name: Install Buildozer
      run: pip3 install buildozer

    - name: Build with retry and timeout
      run: |
        export BUILDODER_DOWNLOAD_TIMEOUT=300
        for i in 1 2 3; do
          echo "Build attempt $i"
          timeout 20m buildozer -v android debug && break
          echo "Build failed or timed out, retrying..."
          sleep 10
        done

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: vahot-app
        path: bin/*.apk
