name: Build APK

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Build with Buildozer Action
      uses: artem-solovev/buildozer-action@v1
      with:
        buildozer-version: stable
        target: android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app
        path: bin/*.apk
