name: Build Android APK with Docker

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build using official Kivy Docker
      run: |
        docker run --rm \
          -v $(pwd):/app \
          -w /app \
          -e BUILDOZER_ALLOW_ROOT=1 \
          kivyorg/buildozer:latest \
          buildozer -v android debug

    - name: Build using official Kivy Docker
      run: |
        docker run --rm \
          -v $(pwd):/app \
          -w /app \
          -e BUILDOZER_ALLOW_ROOT=1 \
          kivyorg/buildozer:latest \
          buildozer --yes -v android debug
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: vahot-app
        path: bin/*.apk
