name: Build Android APK

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4

    - name: Build with Python 3.8 Docker
      run: |
        docker build -t buildozer-py38 .
        docker run --rm \
          -v $(pwd):/app \
          -w /app \
          buildozer-py38 \
          buildozer -v android debug
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: vahot-app
        path: bin/*.apk
