 - name: Build using custom Docker
      run: |
        docker build -t my-buildozer .
        docker run --rm \
          -v $(pwd):/app \
          -w /app \
          my-buildozer \
          buildozer -v android debug

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build using Docker
      run: |
        docker run --rm \
          -v $(pwd):/app \
          -w /app \
          kivy/buildozer:latest \
          buildozer -v android debug
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: vahot-app
        path: bin/*.apk
