name: Build Android APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build using Kivy Docker image
      run: |
        docker run --rm \
          -v "$(pwd)":/src \
          -w /src \
          kivy/kivy:latest \
          /bin/bash -c "
          pip install buildozer &&
          buildozer -v android debug
          "

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: VahotApp-APK
        path: bin/*.apk
        retention-days: 30
