name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache Buildozer and Gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.buildozer
          ~/.gradle
        key: ${{ runner.os }}-android-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-android-

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip openjdk-8-jdk git zip unzip wget

    - name: Install Buildozer and Cython
      run: |
        pip3 install buildozer cython

    - name: Build APK with retries
      run: |
        export BUILDODER_DOWNLOAD_TIMEOUT=600
        for i in 1 2 3; do
          echo "Build attempt $i"
          timeout 45m buildozer -v android debug && break
          echo "Build failed or timed out, retrying..."
          sleep 30
        done

    - name: Find and list APK files
      run: |
        echo "=== Searching for APK files ==="
        find . -name "*.apk" -type f
        echo "=== Contents of current directory ==="
        ls -la
        echo "=== Contents of .buildozer ==="
        ls -la .buildozer/android/platform/*/build/outputs/apk/ 2>/dev/null || echo "APK directory not found"

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: bin/*.apk
