name: Build Android APK

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-11-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev

    - name: Setup Android SDK and accept licenses
      run: |
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        
        # Установите command-line tools если нужно
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        mkdir -p cmdline-tools
        unzip -q cmdline-tools.zip -d cmdline-tools
        mv cmdline-tools/cmdline-tools cmdline-tools/latest
        
        # Примите лицензии
        yes | cmdline-tools/latest/bin/sdkmanager --licenses

    - name: Install Buildozer
      run: |
        pip3 install --upgrade buildozer cython virtualenv

    - name: Build with Buildozer
      run: |
        buildozer -v android debug
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: vahot-app
        path: bin/*.apk
