name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build APK with Buildozer
      uses: artem-solovev/buildozer-action@v1
      id: buildozer
      with:
        workdir: .
        buildozer_version: stable

    - name: Upload APK artifact
      uses: actions/upload-artifact@v2
      with:
        name: VahotApp-APK
        path: bin/*.apk
